name: Compile HyperDrive Editor

on:
  push:
    branches: [ main ]
    paths:
      - 'vs code/**'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Enable Corepack for Yarn
        run: corepack enable

      - name: Install Dependencies
        working-directory: ./"vs code"
        run: yarn install

      - name: Compile and Build Editor
        working-directory: ./"vs code"
        # Using vscode-win32-x64-min to create the OSS minified build
        run: yarn gulp vscode-win32-x64-min
        
      - name: Zip Compiled Editor
        run: Compress-Archive -Path "../VSCode-win32-x64/*" -DestinationPath "../HyperDrive-Editor.zip"
        working-directory: ./"vs code"

      - name: Upload Compiled Editor
        uses: actions/upload-artifact@v4
        with:
          name: HyperDrive-Editor-Windows
          path: HyperDrive-Editor.zip
